# questions.toml


[aws]
label = "AWS"

[[aws.questions]]
question = "Which AWS service reduces network latency?"
answers = ["Amazon CloudFront"]
alternatives = ["AWS Transit Gateway  ", "AWS Direct Connect", "Elastic Load Balancing"]
explanation = """
CloudFront offers a cache to improve latency and lower the load on your origin servers. Caching static content gives you the performance and scale that you need to give viewers a fast and reliable experience when visiting your website.
"""

[[aws.questions]]
question = "What kind of database is AWS DynamoDB?"
answers = ["NoSQL"]
alternatives = ["Relational database ", "MongoDB", "Document database"]
hint = "KEY VALUES."
explanation = """
Amazon DynamoDB is a fully managed, serverless, key-value NoSQL database designed to run high-performance applications at any scale. DynamoDB offers built-in security, continuous backups, automated multi-Region replication, in-memory caching, and data import and export tools.
"""

[[aws.questions]]
question = "What are Edge Locations??"
answers = ["Data centers that deliver data fast to the users"]
alternatives = ["Physical hard drives", "Data centers that store petabytes of data", "AWS Regions"]
explanation = """
AWS edge locations provide an additional layer of network infrastructure that provides these benefits to any web application that uses Amazon CloudFront, Global Accelerator and Amazon Route 53. With these services, you can comprehensively protect on the edge your applications running from AWS Regions.
"""

[[aws.questions]]
question = "Which service sends and receives messages between application components?"
answers = ["AWS Simple Queue Service (AWS SQS)"]
alternatives = ["AWS Lambda", "AWS Snowmbile", "AWS CloudTrail"]
hint = "its quite simple"
explanation = """
Amazon SQS is the AWS service that allows application components to communicate in the cloud. You will use the Amazon SQS console to create and configure a message queue, send a message, receive and delete that message, and then delete the queue.
"""

[[aws.questions]]
question = "What is the purpose of AWS Organizations service?"
answers = ["AWS Organizations helps you manage multiple AWS Accounts"]
alternatives = ["AWS Organizations optimizes your system performance", "AWS Organizations organizes your services and makes service usage reports", "AWS Organizations groups your applications and manages them"]
hint = "What are accounts part of?"
explanation = """
IAM provides granular control over users and roles in individual accounts. AWS Organizations expands that control to the account level by giving you control over what users and roles in an account or a group of accounts can do.
"""

[[aws.questions]]
question = "What service manages web infastructure??"
answers = ["AWS Elastic Beanstalk"]
alternatives = ["Redshift", "s3","AWS Glue"]
hint = "Bends to your every need"
explanation = """
Elastic Beanstalk is a service for deploying and scaling web applications and services. Upload your code and Elastic Beanstalk automatically handles the deployment—from capacity provisioning, load balancing, and auto scaling to application health monitoring.
"""

[[aws.questions]]
question = "What is AWS EC2?"
answers = ["a virtual server in the AWS Cloud"]
alternatives = ["AWS EC2 is a serverless compute service", "AWS EC2 is a data center", "AWS EC2 is a resource monitoring service"]
hint = "Elastic Compute Cloud"
explanation = """
Amazon Elastic Compute Cloud (Amazon EC2) is a web service that provides secure, resizable compute capacity in the cloud. It is designed to make web-scale cloud computing easier for developers. Amazon EC2's simple web service interface allows you to obtain and configure capacity with minimal friction.
"""

[[aws.questions]]
question = "Which Amazon S3 storage class has the lowest cost?"
answers = ["S3 Glacier Deep Archive"]
alternatives = ["S3 Inteligent-Tiering", "S3 Standard", "S3 Enterprise"]
hint = "Prices below zero"
explanation = """
S3 Glacier Deep Archive is Amazon S3's lowest-cost storage class and supports long-term retention and digital preservation for data that may be accessed once or twice in a year. It's around $. 005 per GB per month, or $5/TB per month to store your data.
"""

[[aws.questions]]
question = "What is AWS EFS?"
answers = ["AWS Elastic File System"]
alternatives = ["AWS Enterprise File System", "AWS Efficient File System", "AWS Efficient File Sort"]
hint = "Bend your mind"
explanation = """
Amazon EFS provides shared file storage for use with compute instances in the AWS Cloud and on-premises servers. Applications that require shared file access can use Amazon EFS for reliable file storage delivering high aggregate throughput to thousands of clients simultaneously.
"""

[[aws.questions]]
question = "Which of the following is AWS Migration Strategy?"
answers = ["Replatforming "]
alternatives = ["Auditability", "Governance"]
hint = "A migration strategy is the approach used to migrate a workload into the AWS Cloud. There are seven migration strategies for moving applications to the cloud, known as the 7 Rs:"
explanation = """
This strategy is also known as lift, tinker, and shift or lift and reshape. Using this migration strategy, you move the application to the cloud, and you introduce some level of optimization in order to operate the application efficiently, to reduce costs, or to take advantage of cloud capabilities. For example, you might replatform a Microsoft SQL Server database to Amazon RDS for SQL Server.
"""
